apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: db
  namespace: student99
spec:
  containers:
  - name: db
    image: vovolkov/db
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: webapp-secret
          key: DBUSER
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: webapp-secret
          key: DBPASS
    - name: POSTGRES_DB
      valueFrom:
        secretKeyRef:
          name: webapp-secret
          key: DBNAME
