apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  initContainers:
  - name: pingdb
    envFrom:
    - secretRef:
        name: webapp-secret
    - configMapRef:
        name: webapp-configmap
    image: vovolkov/webapp
    command: ["python3","-u","/app/pingdb.py"]
  containers:
  - name: webapp
    image: vovolkov/webapp
    ports:
    - containerPort: 80
    imagePullPolicy: Always
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10
    envFrom:
    - configMapRef:
        name: webapp-configmap
    - secretRef:
        name: webapp-secret
