apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
     - port: 80
       nodePort: "help: 32000 + StudentNum"
