apiVersion: v1
kind: Service
metadata:
  name: supermario
spec:
  selector:
    app: supermario
  type: NodePort
  ports:
     - port: 8080
       nodePort: 32080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supermario
  template:
    metadata:
      labels:
        app: supermario
    spec:
      containers:
      - name: mario-container
        image: pengbai/docker-supermario
        ports:
        - containerPort: 8080
